// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Data: typeof import('./src/components/Data.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    SearchBar: typeof import('./src/components/dataview/SearchBar.vue')['default']
    SkipData: typeof import('./src/components/dataview/SkipData.vue')['default']
    StageData: typeof import('./src/components/dataview/StageData.vue')['default']
    TagData: typeof import('./src/components/dataview/TagData.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }

}
